version: '3.3'

services:
  db:
    image: postgres:13.4
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=gv
      - POSTGRES_DB=fvds
  web:
    build: .
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    restart: always
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  redis:
    image: redis:6.2-alpine
    expose:
      - 6379

  celery:
    build: .
    container_name: 'app_celery'
    restart: always
    command: celery -A tasks worker -B
    volumes:
      - .:/app
    links:
      - redis
    depends_on:
      - web
      - redis


volumes:
  postgres_data: